-- V1__initial_schema.sql
-- Initial MySQL database schema for CDUP (Customer Data Update Portal)
-- Migrated from Oracle to MySQL

-- Users table for login and authentication
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    department VARCHAR(100),
    role VARCHAR(20) NOT NULL DEFAULT 'AGENT',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_active BOOLEAN DEFAULT TRUE,
    account_locked BOOLEAN DEFAULT FALSE,
    failed_attempts INT DEFAULT 0,
    last_login DATETIME,
    password_changed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    INDEX idx_users_username (username),
    INDEX idx_users_email (email),
    INDEX idx_users_role (role),
    INDEX idx_users_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Customer Update Requests table (main business entity)
CREATE TABLE IF NOT EXISTS customer_update_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    complaint_number VARCHAR(50),
    cnic VARCHAR(15) NOT NULL,
    mobile_number VARCHAR(15) NOT NULL,
    next_of_kin VARCHAR(100),
    email VARCHAR(100),
    father_name VARCHAR(100),
    mother_name VARCHAR(100),
    source_of_income VARCHAR(50),
    purpose_of_account VARCHAR(50),
    latitude VARCHAR(20),
    longitude VARCHAR(20),
    cc_remarks TEXT,
    selfie_cnic_verified BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    submitted_by BIGINT NOT NULL,
    approved_by BIGINT,
    processed_by BIGINT,
    approval_comments TEXT,
    rejection_reason TEXT,
    processing_result TEXT,
    db_execution_result TEXT,
    error_message VARCHAR(1000),
    batch_id BIGINT,
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    approved_at DATETIME,
    processed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (processed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_requests_cnic (cnic),
    INDEX idx_requests_mobile (mobile_number),
    INDEX idx_requests_status (status),
    INDEX idx_requests_submitted_by (submitted_by),
    INDEX idx_requests_created_at (created_at),
    INDEX idx_requests_batch_id (batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
